const cards = document.querySelector("#districtBusinessCards");
const results = document.querySelector("#districtResults");
const empty = document.querySelector("#districtEmpty");
const search = document.querySelector("#districtSearch");
const location = document.querySelector("#districtLocation");
const sideLocation = document.querySelector("#districtSideLocation");
const category = document.querySelector("#districtCategory");
const services = document.querySelector("#districtServices");
const verified = document.querySelector("#districtVerified");
const form = document.querySelector("#districtSearchForm");
const filters = document.querySelector("#districtFilters");
let businesses = [];
const normalise = (value) => String(value || "").trim().toLowerCase();
const serviceList = (value) => Array.isArray(value) ? value : String(value || "").split(",");
const titleCase = (value) => String(value || "Business").replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

const syncLocation = (source) => { if (source === location && sideLocation) sideLocation.value = location.value; if (source === sideLocation && location) location.value = sideLocation.value; };
const matches = (business) => {
  const profile = business.businessProfile || {};
  const query = normalise([search.value, services.value].filter(Boolean).join(" "));
  const selectedLocation = normalise(location.value || sideLocation.value);
  const selectedCategory = normalise(category.value);
  const haystack = normalise([business.workingName, business.accountCategory, profile.location, profile.description, serviceList(profile.services).join(" ")].join(" "));
  return (!query || haystack.includes(query)) && (!selectedLocation || normalise(profile.location).includes(selectedLocation)) && (!selectedCategory || normalise(business.accountCategory) === selectedCategory) && (!verified.checked || business.applicationStatus === "approved");
};
const cardFor = (business) => {
  const profile = business.businessProfile || {};
  const name = String(business.workingName || "Business").trim();
  const initials = name.split(/\s+/).map((word) => word[0] || "").slice(0, 2).join("").toUpperCase();
  const card = document.createElement("article"); card.className = "district-business-card";
  const link = document.createElement("a"); link.href = "business-public.html?id=" + encodeURIComponent(business.id); link.setAttribute("aria-label", "View " + name);
  const media = document.createElement("div"); media.className = "district-business-media"; media.textContent = initials;
  const badge = document.createElement("span"); badge.className = "district-business-badge"; badge.textContent = "Verified"; media.append(badge);
  const body = document.createElement("div"); body.className = "district-business-body";
  const heading = document.createElement("h3"); heading.textContent = name;
  const kind = document.createElement("p"); kind.className = "district-business-kind"; kind.textContent = titleCase(business.accountCategory);
  const details = document.createElement("p"); details.className = "district-business-details"; details.textContent = profile.location || "Australia";
  const meta = document.createElement("div"); meta.className = "district-business-meta"; meta.innerHTML = '<span aria-label="Featured business">★★★★★ <small>Featured</small></span><span>Open for enquiries</span>';
  const save = document.createElement("button"); save.type = "button"; save.className = "district-save"; save.setAttribute("aria-label", "Save " + name); save.setAttribute("aria-pressed", "false"); save.textContent = "♡";
  save.addEventListener("click", (event) => { event.preventDefault(); const isSaved = save.getAttribute("aria-pressed") === "true"; save.setAttribute("aria-pressed", String(!isSaved)); save.textContent = isSaved ? "♡" : "♥"; });
  body.append(heading, kind, details, meta, save); link.append(media, body); card.append(link); return card;
};
const render = () => { const visible = businesses.filter(matches); cards.replaceChildren(...visible.map(cardFor)); empty.hidden = visible.length !== 0; results.textContent = visible.length ? visible.length + (visible.length === 1 ? " business" : " businesses") + " in the District" : "No matching businesses"; };
const setStats = () => { const locations = new Set(), categories = new Set(); businesses.forEach((business) => { const profile = business.businessProfile || {}; if (profile.location) locations.add(profile.location); if (business.accountCategory) categories.add(business.accountCategory); }); document.querySelector("#districtBusinessCount").textContent = businesses.length; document.querySelector("#districtCityCount").textContent = locations.size; document.querySelector("#districtCategoryCount").textContent = categories.size; };
const runQuery = (value) => { search.value = value || ""; render(); document.querySelector("#businesses")?.scrollIntoView({ behavior: "smooth", block: "start" }); };
form.addEventListener("submit", (event) => { event.preventDefault(); syncLocation(location); render(); document.querySelector("#businesses")?.scrollIntoView({ behavior: "smooth", block: "start" }); });
[search, services].forEach((input) => input.addEventListener("input", render)); [location, sideLocation, category, verified].forEach((input) => input.addEventListener("change", () => { if (input === location || input === sideLocation) syncLocation(input); render(); }));
filters.addEventListener("reset", () => window.setTimeout(() => { location.value = ""; sideLocation.value = ""; render(); }, 0));
document.querySelectorAll("[data-district-query]").forEach((link) => link.addEventListener("click", (event) => { if (link.tagName === "A") event.preventDefault(); runQuery(link.dataset.districtQuery); }));
document.querySelectorAll("[data-district-category]").forEach((link) => link.addEventListener("click", (event) => { event.preventDefault(); category.value = link.dataset.districtCategory; document.querySelectorAll("[data-district-category]").forEach((item) => item.classList.toggle("is-current", item === link)); render(); document.querySelector("#businesses")?.scrollIntoView({ behavior: "smooth", block: "start" }); }));
fetch("/api/directory/businesses").then((response) => response.ok ? response.json() : Promise.reject(new Error("Business directory unavailable"))).then((result) => { businesses = Array.isArray(result.businesses) ? result.businesses : []; setStats(); render(); }).catch(() => { businesses = []; setStats(); render(); });
